version: '3'
services:
  chess-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - ./prisma:/app/prisma 