services:
  - type: web
    name: chess-site
    env: node
    plan: free
    buildCommand: ./prepare-production.sh
    startCommand: npm run start:unified
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        fromService:
          type: web
          name: chess-site
          envVarKey: RENDER_EXTERNAL_URL 