name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v1.0.0/render-cli_1.0.0_linux_amd64.tar.gz -o render.tar.gz
          tar -xzf render.tar.gz
          chmod +x render
          sudo mv render /usr/local/bin/

      - name: Deploy to Render
        run: |
          echo "Triggering deploy on Render..."
          curl -X POST "${{ secrets.RENDER_API_DEPLOY_HOOK }}"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} 